version: "3.8"
services:
   
    roach1:
        container_name: cockroachdb1
        image: cockroachdb/cockroach:v20.2.10
        volumes:
           - volume1:/cockroach/cockroach-data
        command: start --insecure --advertise-addr=roach1:26257 --join=roach2:26257,roach3:26257
        ports:
           - 26257:26257
           - 8080:8080
        networks:
            - roachnet

    roach2:
        container_name: cockroachdb2
        restart: always
        image: cockroachdb/cockroach:v20.2.10
        volumes:
           - volume2:/cockroach/cockroach-data
        command: start --insecure --advertise-addr=roach2:26257 --join=roach1:26257,node_3:26257
        ports:
            - 26258:26257
            - 8088:8080
        networks:
            - roachnet
    
    roach3:
        container_name: cockroachdb3
        restart: always
        image: cockroachdb/cockroach:v20.2.10
        volumes:
            - volume3:/cockroach/cockroach-data
        command: start --insecure --advertise-addr=roach3:26257 --join=roach1:26257,roach2:26257
        ports:
            - 26259:26257
            - 8089:8080
        networks:
            - roachnet

networks:
    roachnet:
volumes:
    volume1:
    volume2:
    volume3:
