version: "3.8"
services:
   
    node_1:
        container_name: node_1
        image: cockroachdb/cockroach:v20.2.10
        volumes:
           - ./data/node_1:/cockroach/cockroach-data
        command: start --insecure --join=node_1,node_2,node_3 --listen-addr=node_1
        ports:
           - "26257:26257"
           - "8080:8080"
        networks:
            cockroachdb_net:
                aliases:
                   - node_1

    node_2:
        container_name: node_2
        image: cockroachdb/cockroach:v20.2.10
        volumes:
           - ./data/node_2:/cockroach/cockroach-data
        command: start --insecure --join=node_1,node_2,node_3 --listen-addr=node_2
        networks:
            cockroachdb_net:
                aliases:
                   - node_2
    
    node_3:
        container_name: node_3
        image: cockroachdb/cockroach:v20.2.10
        volumes:
            - ./data/node_3:/cockroach/cockroach-data
        command: start --insecure --join=node_1,node_2,node_3 --listen-addr=node_3
        networks:
            cockroachdb_net:
                aliases:
                    - node_3

networks:
    cockroachdb_net:
        driver: bridge